// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiBfxt1piutkasxWR0Hs14C4Wf0TSppr8',
    appId: '1:844969179587:web:0d3eac36f0160569846576',
    messagingSenderId: '844969179587',
    projectId: 'kafe-40b9f',
    authDomain: 'kafe-40b9f.firebaseapp.com',
    storageBucket: 'kafe-40b9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6wM5XrhUP4v1hyy4tBwgSVX2oYEE0E_c',
    appId: '1:844969179587:android:f59671d1c86e4232846576',
    messagingSenderId: '844969179587',
    projectId: 'kafe-40b9f',
    storageBucket: 'kafe-40b9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDXWD6xwRixN-zmnRZl57F0K51bMftwTw',
    appId: '1:844969179587:ios:d0f54d679c3249f0846576',
    messagingSenderId: '844969179587',
    projectId: 'kafe-40b9f',
    storageBucket: 'kafe-40b9f.firebasestorage.app',
    iosBundleId: 'com.example.kafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDXWD6xwRixN-zmnRZl57F0K51bMftwTw',
    appId: '1:844969179587:ios:d0f54d679c3249f0846576',
    messagingSenderId: '844969179587',
    projectId: 'kafe-40b9f',
    storageBucket: 'kafe-40b9f.firebasestorage.app',
    iosBundleId: 'com.example.kafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiBfxt1piutkasxWR0Hs14C4Wf0TSppr8',
    appId: '1:844969179587:web:a7889ad0058575bb846576',
    messagingSenderId: '844969179587',
    projectId: 'kafe-40b9f',
    authDomain: 'kafe-40b9f.firebaseapp.com',
    storageBucket: 'kafe-40b9f.firebasestorage.app',
  );

}