name: Création de l'Apk
on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: Build & release
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Java env
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/flutter/.pub
            **/flutter/bin
            **/flutter/packages
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-  # Matches any previous cache key
      - name: Set up Flutter env
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          architecture: x64
      - name: Add Flutter to PATH
        run: echo "${{ runner.tool_cache }}/flutter/3.22.2-stable/x64/bin" >> $GITHUB_PATH
      - name: Set up project dependencies
        run: flutter pub get
      - name: Check flutter installation
        run: flutter --version
      - name: Build apk
        run: flutter build apk --release
      - name: Set up release files
        run: mkdir staging
      - name: Copy files to staging directory
        run: mv build/app/outputs/flutter-apk/app-release.apk staging/Chti_Kafé.apk
      - name: Create and upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chti_Kafé
          path: staging/Chti_Kafé.apk